ToDoList/Models/TodoList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;


namespace ToDoList.Models
{

    public enum TaskStatus
    {
        Canceled,
        Done,
        Delayed,
        Ongoing,
    }

    public class TodoList
    {
        public int ID { get; set; }
        public string Task { get; set; }
        public int Priority { get; set; }

        [Display(Name = "Start Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime StartDate { get; set; }

        [Display(Name = "End Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime EndDate { get; set; }
        public String Status { get; set; }
        public string User { get; set; }


    }

    public class TodoListDBContext : DbContext
    {
        public DbSet<TodoList> TodoList { get; set; }
    }
}

ToDoList/Controllers/ToDoListController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ToDoList.Models;

namespace ToDoList.Controllers
{
    public class ToDoListController : Controller
    {
        private TodoListDBContext db = new TodoListDBContext();

        // GET: /ToDoList/
        public ActionResult Index(string sortOrder, string searchString)
        {
            var tasks = from s in db.TodoList
                        select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                tasks = tasks.Where(s => s.Task.Contains(searchString));
            }
            else {
                ViewBag.PrioritySortParam = String.IsNullOrEmpty(sortOrder) ? "Priority" : "";
                ViewBag.DateSortParm = sortOrder;

                switch (sortOrder)
                {
                    case "Priority":
                        tasks = tasks.OrderBy(s => s.Priority);
                        break;
                    case "End Date":
                        tasks = tasks.OrderBy(s => s.EndDate);
                        break;
                    case "Start Date":
                    default:
                        tasks = tasks.OrderBy(s => s.StartDate);
                        break;
                }            
            }
            
            return View(tasks.ToList());
        }

        // GET: /ToDoList/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoList todolist = db.TodoList.Find(id);
            if (todolist == null)
            {
                return HttpNotFound();
            }
            return View(todolist);
        }

        // GET: /ToDoList/Create
        public ActionResult Create()
        {
            ViewBag.TaskStatus = SelectTaskStatus();
            return View();
        }

        // POST: /ToDoList/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Task,Priority,StartDate,EndDate,Status,User")] TodoList todolist, string TaskStatus)
        {
            if (ModelState.IsValid)
            {
                todolist.Status = TaskStatus;
                db.TodoList.Add(todolist);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(todolist);
        }

        // GET: /ToDoList/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoList todolist = db.TodoList.Find(id);
            if (todolist == null)
            {
                return HttpNotFound();
            }
            ViewBag.TaskStatus = SelectTaskStatus();
            return View(todolist);
        }

        // POST: /ToDoList/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Task,Priority,StartDate,EndDate,Status,User")] TodoList todolist, string TaskStatus)
        {
            if (ModelState.IsValid)
            {
                todolist.Status = TaskStatus;
                db.Entry(todolist).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(todolist);
        }

        // GET: /ToDoList/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TodoList todolist = db.TodoList.Find(id);
            if (todolist == null)
            {
                return HttpNotFound();
            }
            return View(todolist);
        }

        // POST: /ToDoList/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TodoList todolist = db.TodoList.Find(id);
            db.TodoList.Remove(todolist);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public IEnumerable<SelectListItem> SelectTaskStatus()
        {
            IEnumerable<TaskStatus> values = Enum.GetValues(typeof(TaskStatus)).Cast<TaskStatus>();
            IEnumerable<SelectListItem> items = 
                from value in values
                select new SelectListItem
                {
                    Text = value.ToString(),
                    Value = value.ToString(),
                    Selected = value == TaskStatus.Ongoing,
                };

            return items;
        }
    }
}

ToDoList/Views/ToDoList/Create.cshtml
@model ToDoList.Models.TodoList

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TodoList</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.User, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User)
                @Html.ValidationMessageFor(model => model.User)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Task, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Task)
                @Html.ValidationMessageFor(model => model.Task)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority)
                @Html.ValidationMessageFor(model => model.Priority)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TaskStatus")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoList/Delete.cshtml
@model ToDoList.Models.TodoList

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TodoList</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Task)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Task)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ToDoList/Views/ToDoList/Details.cshtml
@model ToDoList.Models.TodoList

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>TodoList</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Task)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Task)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Priority)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Priority)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StartDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ToDoList/Views/ToDoList/Edit.cshtml
@model ToDoList.Models.TodoList

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>TodoList</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.User, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.User)
                @Html.ValidationMessageFor(model => model.User)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Task, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Task)
                @Html.ValidationMessageFor(model => model.Task)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Priority, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Priority)
                @Html.ValidationMessageFor(model => model.Priority)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDate)
                @Html.ValidationMessageFor(model => model.StartDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDate)
                @Html.ValidationMessageFor(model => model.EndDate)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TaskStatus")
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ToDoList/Views/ToDoList/Index.cshtml
@model IEnumerable<ToDoList.Models.TodoList>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")

    @using (Html.BeginForm("Index", "ToDoList", FormMethod.Get))
{
    <p>
        Task: @Html.TextBox("SearchString") <br />
        <br />
        <input type="submit" value="Filter" />
    </p>
    }


</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.User)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Task)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Priority)
            @Html.ActionLink("▲", "Index", new { Style = "color:#cdcdcd;", sortOrder = ViewBag.PrioritySortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StartDate)
            @Html.ActionLink("▲", "Index", new { sortOrder = "Start Date" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EndDate)
            @Html.ActionLink("▲", "Index", new { sortOrder = "End Date" })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.User)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Task)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Priority)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StartDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EndDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>